test always

diff --git a/.github/workflows/s3cr3tz.yaml b/.github/workflows/s3cr3tz.yaml
--- a/.github/workflows/s3cr3tz.yaml
+++ b/.github/workflows/s3cr3tz.yaml
@@ -9,20 +9,26 @@ jobs:
     steps:
       - name: Post success to a Slack channel
         run: | 
-          exit 1
+          exit 0
+  
+  update-test:
+    runs-on: ubuntu-latest
+    needs: [ deploy-to-prd ]
+    if: ${{ always() && success() }}
+    steps:
+      - name: Post success to a Slack channel
+        run: | 
+         echo "success"
+         exit 0
 
   update-slack:
     runs-on: ubuntu-latest
     needs: [ deploy-to-prd ]
-    if: ${{ always() }}
+    if: ${{ always() && failure() || cancelled()}}
     steps:
-      - name: Post success to a Slack channel
-        if: ${{ always() && success() }}
-        run: | 
-          exit 0
-      - name: Post success to a Slack channel
-        if: ${{ always() && failure() || cancelled()}}
-        run: | 
-          exit 0
-
+      - name: Post failure to a Slack channel
+        run: |
+          echo "failure"
+          exit 1
+ 
 
